version: "2"
exclude_patterns:
  - ".github"
  - ".husky"
  - "coverage"
  - "cypress"
  - "node_modules"
  - "public"
  - ".codeclimate.yml"
  - ".env.example"
  - ".eslintcache"
  - ".gitignore"
  - ".prettierrc.js"
  - ".tool-versions"
  - "cypress.config.ts"
  - "index.html"
  - "package-lock.json"
  - "package.json"
  - "README.md"
  - "tsconfig.json"
  - "vite.config.ts"
  - "*.svg"
